drop SEQUENCE COUPON_SEQ;
drop SEQUENCE NOTICE_SEQ;
drop SEQUENCE COMMENT_SEQ;
drop SEQUENCE FILE_SEQ;
drop SEQUENCE ZIPCODE_SEQ;
drop SEQUENCE MEMBER_SEQ;
drop SEQUENCE QA_SEQ;
drop SEQUENCE THEATER_SEQ;
drop SEQUENCE FQ_SEQ;
drop SEQUENCE DIRECTOR_SEQ;
drop SEQUENCE ACTOR_SEQ;
drop SEQUENCE PRODUCTION_SEQ;
drop SEQUENCE SCHEDULE_SEQ;
drop SEQUENCE TICKET_SEQ;
drop SEQUENCE MOVIE_SEQ;
drop SEQUENCE EVENT_SEQ;
drop SEQUENCE WINNER_SEQ;
drop SEQUENCE MOVIEROOM_SEQ;

--쿠폰번호
create SEQUENCE COUPON_SEQ;
--공지번호
create SEQUENCE NOTICE_SEQ;
--코멘트번호
create SEQUENCE COMMENT_SEQ;
--파일번호
create SEQUENCE FILE_SEQ;
--우편번호
create SEQUENCE ZIPCODE_SEQ;
--회원번호
create SEQUENCE MEMBER_SEQ;
--QA번호
create SEQUENCE QA_SEQ;
--극장번호
create SEQUENCE THEATER_SEQ;
--FQ번호
create SEQUENCE FQ_SEQ;
--감독번호
create SEQUENCE DIRECTOR_SEQ;
--배우번호
create SEQUENCE ACTOR_SEQ;
--제작사번호
create SEQUENCE PRODUCTION_SEQ;
--스케줄번호
create SEQUENCE SCHEDULE_SEQ;
--티켓번호
create SEQUENCE TICKET_SEQ;
--영화번호
create SEQUENCE MOVIE_SEQ;
--이벤트번호
create SEQUENCE EVENT_SEQ;
--당첨자번호
create SEQUENCE WINNER_SEQ;
--상영관번호
create SEQUENCE MOVIEROOM_SEQ;